version: "3"
services:
  contracts-test:
    build: "./truffle"
    container_name: contracts-test
    ports:
      - "8000:8000"
    depends_on:
      - ganache
    restart: "on-failure"
    command: truffle test
  ganache:
    container_name: ganache
    image: "trufflesuite/ganache-cli"
    ports:
      - "8545:8545"
